name: Linting

on:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  black-formatted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  
  py-linted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pylint
        run: pip3 install pylint
      - name: Run pylint
        run: pylint custom_components/g4s_alarm/

  imports-sorted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install isort
        run: pip3 install isort
      - name: Run isor
        run: isort . --diff --check --profile black

            